packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - "@scarf/scarf"
  - esbuild
  - unrs-resolver
